### ISSUE TITLE
Improve reading of CSV files

### ISSUE THREAD

**Issue by Mibblez** [Mibblez/Neuromorphic-Data-Processing#16]
### Summary

- Update reading of CSV files to use `pandas.read_csv()` so that large CSVs don't cause python to explode
- **get_plotting_data.py -> SpatialCsvData.from_csv()** has a mostly complete implementation. Base work off of that
- Work to be done in branch `update-FileReading`
- Make a new venv and make sure you're using python 3.11

### TODO
- [ ] **get_plotting_data.py -> SpatialCsvData.from_csv()**
   - [x] Throw error when CSV is empty
   - [x] Throw error when header does not contain necessary columns (maybe use **plotting_helper.py -> check_aedat_csv_format()**)
   - [ ] Update tests accordingly
- [ ] **get_plotting_data.py -> read_aedat_csv**
   - [ ] Update CSV reading to use `pandas.read_csv()`
   - [ ] Update camera type handling to be similar to `SpatialCsvData.from_csv()`
- [ ] **event_density.py -> main()**
   - [ ] Update CSV reading to use `pandas.read_csv()`
- [ ] **spike_graph.py -> get_activity_area()**
   - [ ] Update CSV reading to use `pandas.read_csv()`
- [ ] **process_CSV.py -> process_csv_files()**
   - [ ] Update CSV reading to use `pandas.read_csv()`
- [ ] **extract_pgm.py -> main()**
   - [ ] Update CSV reading to use `pandas.read_csv()`
